#!/bin/sh

#  credentials
#  Prints the current credentials for Socks5Proxy and Tor HashedControlPassword
#
#  Created by Adam Gautier on 11/03/18.
#  Copyright © 2018 Adam Gautier. All rights reserved.
#
#
/bin/cat /etc/tor/torrc | grep Socks5ProxyUsername
/bin/cat /etc/tor/torrc | grep Socks5ProxyPassword
echo "ControlPassword $(cat /etc/tor/torrc.secret)"
# rm -rf /etc/tor/torrc.secret
/bin/cat /etc/tor/torrc | grep HashedControlPassword

